import 'package:flutter/material.dart';

class CryptoNews {
  final String title;
  final String summary;
  final String source;
  final DateTime publishDate;

  CryptoNews({
    required this.title,
    required this.summary,
    required this.source,
    required this.publishDate,
  });
}

final List<CryptoNews> cryptoNewsList = [
  CryptoNews(
    title: '比特币突破40000美元大关',
    summary: '在机构投资者的推动下，比特币价格再创新高，突破40000美元大关。',
    source: '加密货币日报',
    publishDate: DateTime.now().subtract(const Duration(hours: 2)),
  ),
  CryptoNews(
    title: '以太坊2.0升级展顺利',
    summary: '以太坊开发团队宣布，以太坊2.0的升级进展顺利，预计将在今年底完成。',
    source: '区块链新闻网',
    publishDate: DateTime.now().subtract(const Duration(hours: 5)),
  ),
  CryptoNews(
    title: '新加坡推出加密货币交易所监管框架',
    summary: '新加坡金融管理局发布了针对加密货币交易所的新监管框架，旨在提高行业透明度和安全性。',
    source: '亚洲金融时报',
    publishDate: DateTime.now().subtract(const Duration(days: 1)),
  ),
  CryptoNews(
    title: 'DeFi项目总锁仓价值突破500亿美元',
    summary: '去中心化金融（DeFi）项目的总锁仓价值突破500亿美元大关，显示出该领域持续增长的趋势。',
    source: 'DeFi观察',
    publishDate: DateTime.now().subtract(const Duration(days: 2)),
  ),
  CryptoNews(
    title: '美国SEC主席表示将加强加密货币监管',
    summary: '美国证券交易委员会（SEC）主席在国会听证会上表示，将加强对加密货币行业的监管力度。',
    source: '华尔街日报',
    publishDate: DateTime.now().subtract(const Duration(days: 3)),
  ),
  CryptoNews(
    title: '币安推出新的NFT交易平台',
    summary: '全球最大的加密货币交易所币安宣布推出新的NFT交易平台，支持多链资产。',
    source: 'NFT日报',
    publishDate: DateTime.now().subtract(const Duration(days: 4)),
  ),
  CryptoNews(
    title: '卡尔达诺完成重大网络升级',
    summary: '卡尔达诺区块链完成了"阿隆佐"硬分叉升级，引入智能合约功能。',
    source: '区块链技术周刊',
    publishDate: DateTime.now().subtract(const Duration(days: 5)),
  ),
  CryptoNews(
    title: '萨尔瓦多比特币使用率超预期',
    summary: '萨尔瓦多政府报告称，比特币作为法定货币的使用率超过预期，带动经济增长。',
    source: '拉丁美洲经济观察',
    publishDate: DateTime.now().subtract(const Duration(days: 6)),
  ),
  CryptoNews(
    title: '波卡生态系统迎来首批平行链',
    summary: '波卡网络成功拍卖并激活了首批平行链，标志着其生态系统的重要里程碑。',
    source: '多链未来',
    publishDate: DateTime.now().subtract(const Duration(days: 7)),
  ),
  CryptoNews(
    title: '以太坊伦敦硬分叉成功实施',
    summary: '以太坊网络成功实施伦敦硬分叉，引入EIP-1559等重要更新，有望降低gas费。',
    source: '以太坊世界',
    publishDate: DateTime.now().subtract(const Duration(days: 8)),
  ),
  CryptoNews(
    title: '大型科技公司开始接受加密货币支付',
    summary: '多家大型科技公司宣布将开始接受比特币等加密货币作为支付方式，推动主流采用。',
    source: '科技创新报',
    publishDate: DateTime.now().subtract(const Duration(days: 9)),
  ),
  CryptoNews(
    title: 'Layer 2解决方案Optimism上线主网',
    summary: '以太坊Layer 2扩容解决方案Optimism正式上线主网，有望大幅提升交易速度和降低费用。',
    source: '扩容先锋',
    publishDate: DateTime.now().subtract(const Duration(days: 10)),
  ),
  CryptoNews(
    title: '加密货币挖矿向可再生能源转型',
    summary: '越来越多的比特币矿工开始使用可再生能源，以应对环境问题和监管压力。',
    source: '绿色加密',
    publishDate: DateTime.now().subtract(const Duration(days: 11)),
  ),
  CryptoNews(
    title: 'Uniswap V3创下单日交易量新高',
    summary: '去中心化交易所Uniswap V3版本创下单日交易量新高，达到50亿美元。',
    source: 'DEX观察',
    publishDate: DateTime.now().subtract(const Duration(days: 12)),
  ),
  CryptoNews(
    title: '首个比特币期货ETF在美国获批',
    summary: '美国证券交易委员会批准了首个比特币期货ETF，标志着加密货币进入传统金融市场的重要一步。',
    source: '金融创新前沿',
    publishDate: DateTime.now().subtract(const Duration(days: 13)),
  ),
  CryptoNews(
    title: 'Solana网络遭遇大规模宕机',
    summary: 'Solana区块链网络因遭受大规模DDoS攻击而宕机17小时，引发对其稳定性的担忧。',
    source: '区块链安全警报',
    publishDate: DateTime.now().subtract(const Duration(days: 14)),
  ),
  CryptoNews(
    title: '加密艺术品在佳士得拍卖会上创纪录',
    summary: '一件NFT加密艺术品在佳士得拍卖会上以6900万美元的价格成交，创下新的纪录。',
    source: '艺术与科技',
    publishDate: DateTime.now().subtract(const Duration(days: 15)),
  ),
  CryptoNews(
    title: '俄罗斯央行提议禁止加密货币',
    summary: '俄罗斯央行发布报告，建议全面禁止加密货币的使用、挖矿和交易。',
    source: '欧亚经济观察',
    publishDate: DateTime.now().subtract(const Duration(days: 16)),
  ),
  CryptoNews(
    title: 'GameFi项目Axie Infinity用户突破百万',
    summary: '基于区块链的游戏Axie Infinity宣布其活跃用户数量突破100万，展示了GameFi的巨大潜力。',
    source: '游戏金融报告',
    publishDate: DateTime.now().subtract(const Duration(days: 17)),
  ),
  CryptoNews(
    title: '中国数字人民币试点范围进一步扩大',
    summary: '中国人民银行宣布将数字人民币试点范围扩大到更多城市，加速推进央行数字货币发展。',
    source: '中国金融科技',
    publishDate: DateTime.now().subtract(const Duration(days: 18)),
  ),
  CryptoNews(
    title: 'Chainlink推出跨链互操作性协议',
    summary: 'Chainlink发布新的跨链互操作性协议CCIP，旨在实现不同区块链网络之间的无缝通信。',
    source: '互操作性前沿',
    publishDate: DateTime.now().subtract(const Duration(days: 19)),
  ),
  CryptoNews(
    title: '加密货币交易所Coinbase上市纳斯达克',
    summary: '美国最大的加密货币交易所Coinbase在纳斯达克直接上市，市值一度超过1000亿美元。',
    source: '华尔街密报',
    publishDate: DateTime.now().subtract(const Duration(days: 20)),
  ),
  CryptoNews(
    title: '以太坊创始人Vitalik捐赠大量狗狗币',
    summary: '以太坊创始人Vitalik Buterin将价值10亿美元的狗狗币捐赠给印度新冠救援基金。',
    source: '加密慈善观察',
    publishDate: DateTime.now().subtract(const Duration(days: 21)),
  ),
  CryptoNews(
    title: 'El Salvador总统提议采矿使用火山能源',
    summary: 'El Salvador总统Nayib Bukele提议使用地热能源进行比特币挖矿，推动绿色采矿。',
    source: '中美洲科技创新',
    publishDate: DateTime.now().subtract(const Duration(days: 22)),
  ),
  CryptoNews(
    title: '比特币闪电网络容量突破5000个比特币',
    summary: '比特币闪电网络的总容量首次突破5000个比特币，显示第二层解决方案的持续增长。',
    source: '闪电网络观察',
    publishDate: DateTime.now().subtract(const Duration(days: 23)),
  ),
  CryptoNews(
    title: '以太坊合并后质押量突破200万枚',
    summary: '以太坊成功完成向权益证明转型后，网络质押量突破200万枚ETH，彰显投资者信心。',
    source: 'ETH质押日报',
    publishDate: DateTime.now().subtract(const Duration(days: 24)),
  ),
  CryptoNews(
    title: '币安智能链日交易量超越以太坊',
    summary: '币安智能链（BSC）单日交易量首次超越以太坊，成为最活跃的智能合约平台。',
    source: '链上数据分析',
    publishDate: DateTime.now().subtract(const Duration(days: 25)),
  ),
  CryptoNews(
    title: '加密货币总市值再创新高，突破3万亿美元',
    summary: '在比特币和以太坊带动下，全球加密货币市场总值首次突破3万亿美元大关。',
    source: '加密市场周刊',
    publishDate: DateTime.now().subtract(const Duration(days: 26)),
  ),
  CryptoNews(
    title: 'NFT交易平台OpenSea估值达130亿美元',
    summary: 'NFT交易平台OpenSea在最新一轮融资中估值达130亿美元，成为加密独角兽。',
    source: 'NFT商业内幕',
    publishDate: DateTime.now().subtract(const Duration(days: 27)),
  ),
  CryptoNews(
    title: '瑞士苏黎世接受比特币缴纳税款',
    summary: '瑞士金融中心苏黎世宣布，将允许居民使用比特币支付税款，最高限额10万瑞士法郎。',
    source: '欧洲加密前沿',
    publishDate: DateTime.now().subtract(const Duration(days: 28)),
  ),
  CryptoNews(
    title: 'Visa推出加密货币咨询服务',
    summary: '全球支付巨头Visa宣布推出加密货币咨询服务，协助客户制定数字货币战略。',
    source: '支付创新快讯',
    publishDate: DateTime.now().subtract(const Duration(days: 29)),
  ),
  CryptoNews(
    title: 'Polygon用户数量突破1亿',
    summary: 'Layer 2扩容解决方案Polygon宣布其独特地址数量突破1亿，创下新里程碑。',
    source: '扩容解决方案报告',
    publishDate: DateTime.now().subtract(const Duration(days: 30)),
  ),
  CryptoNews(
    title: '美国最大银行摩根大通开设元宇宙分行',
    summary: '摩根大通在去中心化虚拟世界Decentraland开设分行，成为首家进入元宇宙的大型银行。',
    source: '元宇宙金融观察',
    publishDate: DateTime.now().subtract(const Duration(days: 31)),
  ),
  CryptoNews(
    title: '特斯拉重新接受比特币支付',
    summary: '特斯拉CEO埃隆·马斯克宣布，公司将重新接受比特币作为支付方式，前提是使用50%以上可再生能源挖矿。',
    source: '科技巨头加密动向',
    publishDate: DateTime.now().subtract(const Duration(days: 32)),
  ),
  CryptoNews(
    title: '韩国推出全球首个国家级NFT平台',
    summary: '韩国政府宣布推出全球首个国家级NFT平台，旨在推动数字艺术发展和版权保护。',
    source: '亚洲区块链创新',
    publishDate: DateTime.now().subtract(const Duration(days: 33)),
  ),
  CryptoNews(
    title: 'DeFi协议Aave推出机构版产品',
    summary: '领先的DeFi借贷协议Aave推出针对机构投资者的版本，提供KYC和合规功能。',
    source: 'DeFi机构观察',
    publishDate: DateTime.now().subtract(const Duration(days: 34)),
  ),
  CryptoNews(
    title: '加拿大批准首个比特币现货ETF',
    summary: '加拿大证券管理机构批准了北美首个比特币现货ETF，为机构投资者提供新的投资渠道。',
    source: '北美加密ETF跟踪',
    publishDate: DateTime.now().subtract(const Duration(days: 35)),
  ),
  CryptoNews(
    title: '迈阿密市推出城市加密货币MiamiCoin',
    summary: '美国迈阿密市推出自己的加密货币MiamiCoin，30%的挖矿收益将用于城市建设。',
    source: '城市币创新报道',
    publishDate: DateTime.now().subtract(const Duration(days: 36)),
  ),
  CryptoNews(
    title: 'Twitter整合比特币闪电网络小费功能',
    summary: 'Twitter宣布在其平台上整合比特币闪电网络小费功能，允许用户向创作者发送比特币。',
    source: '社交媒体加密化',
    publishDate: DateTime.now().subtract(const Duration(days: 37)),
  ),
  CryptoNews(
    title: '以太坊Layer 2解决方案Arbitrum日交易量破10亿美元',
    summary: '以太坊扩容解决方案Arbitrum单日交易量首次突破10亿美元，显示Layer 2解决方案的强劲需求。',
    source: 'Layer 2数据分析',
    publishDate: DateTime.now().subtract(const Duration(days: 38)),
  ),
  CryptoNews(
    title: '巴西最大电子商务平台接受加密货币支付',
    summary: '巴西最大电子商务平台Mercado Livre宣布将接受比特币和以太坊作为支付方式。',
    source: '拉美加密采用观察',
    publishDate: DateTime.now().subtract(const Duration(days: 39)),
  ),
  CryptoNews(
    title: '欧洲央行启动数字欧元试点项目',
    summary: '欧洲央行正式启动为期两年的数字欧元试点项目，探索央行数字货币的可行性。',
    source: '欧洲金融科技前沿',
    publishDate: DateTime.now().subtract(const Duration(days: 40)),
  ),
  CryptoNews(
    title: 'Filecoin存储容量突破10 EiB',
    summary: '去中心化存储网络Filecoin的总存储容量突破10艾字节（EiB），标志着重要里程碑。',
    source: '去中心化存储观察',
    publishDate: DateTime.now().subtract(const Duration(days: 41)),
  ),
  CryptoNews(
    title: '全球首个加密货币主题ETF在巴西上市',
    summary: '全球首个追踪多种加密货币表现的ETF在巴西证券交易所上市，为投资者提供多元化加密投资工具。',
    source: '创新金融产品报告',
    publishDate: DateTime.now().subtract(const Duration(days: 42)),
  ),
  CryptoNews(
    title: '以太坊2.0质押量突破1000万枚',
    summary: '以太坊2.0信标链上的质押量突破1000万枚ETH，显示社区对网络升级的强烈信心。',
    source: '以太坊生态系统报告',
    publishDate: DateTime.now().subtract(const Duration(days: 43)),
  ),
  CryptoNews(
    title: '加密货币交易所Kraken获得阿联酋经营许可',
    summary: '知名加密货币交易所Kraken获得阿联酋监管机构颁发的经营许可，将在中东地区扩展业务。',
    source: '中东加密监管动态',
    publishDate: DateTime.now().subtract(const Duration(days: 44)),
  ),
  CryptoNews(
    title: 'NFT游戏Sorare与NBA达成合作',
    summary: 'NFT幻想运动平台Sorare宣布与NBA达成合作，将推出基于区块链的篮球收藏卡游戏。',
    source: '体育区块链创新',
    publishDate: DateTime.now().subtract(const Duration(days: 45)),
  ),
  CryptoNews(
    title: '瑞士苏黎世银行推出加密货币托管服务',
    summary: '瑞士传统银行业巨头苏黎世银行宣布推出面向机构客户的加密货币托管服务。',
    source: '传统金融拥抱加密',
    publishDate: DateTime.now().subtract(const Duration(days: 46)),
  ),
  CryptoNews(
    title: 'Cardano生态系统首个DEX上线主网',
    summary: 'Cardano区块链上首个去中心化交易所SundaeSwap正式上线主网，标志着生态系统的重要进展。',
    source: 'Cardano生态周刊',
    publishDate: DateTime.now().subtract(const Duration(days: 47)),
  ),
  CryptoNews(
    title: '比特币挖矿难度创历史新高',
    summary: '比特币网络挖矿难度再创新高，反映出矿工们对网络长期发展的信心增强。',
    source: '比特币网络数据分析',
    publishDate: DateTime.now().subtract(const Duration(days: 48)),
  ),
  CryptoNews(
    title: '去中心化社交平台Lens Protocol启动公测',
    summary: '基于区块链的去中心化社交协议Lens Protocol开始公测，旨在重塑社交媒体生态。',
    source: 'Web3社交前沿',
    publishDate: DateTime.now().subtract(const Duration(days: 49)),
  ),
  CryptoNews(
    title: '澳大利亚最大银行开始提供加密货币交易服务',
    summary: '澳大利亚联邦银行宣布，将通过其移动应用为客户提供加密货币买卖服务。',
    source: '澳洲金融科技观察',
    publishDate: DateTime.now().subtract(const Duration(days: 50)),
  ),
  CryptoNews(
    title: 'Layer 2解决方案zkSync 2.0测试网上线',
    summary: 'zkSync 2.0测试网正式上线，带来更快、更便宜的以太坊扩容解决方案。',
    source: '以太坊扩容前沿',
    publishDate: DateTime.now().subtract(const Duration(days: 51)),
  ),
  CryptoNews(
    title: '加拿大养老基金开始投资加密货币',
    summary: '加拿大第二大养老基金Caisse de dépôt et placement du Québec宣布投资加密货币生态系统。',
    source: '机构加密投资趋势',
    publishDate: DateTime.now().subtract(const Duration(days: 52)),
  ),
  CryptoNews(
    title: 'Cosmos生态系统市值突破1000亿美元',
    summary: 'Cosmos生态系统内的所有项目总市值首次突破1000亿美元，显示出跨链技术的巨大潜力。',
    source: '跨链生态系统报告',
    publishDate: DateTime.now().subtract(const Duration(days: 53)),
  ),
  CryptoNews(
    title: '迪拜将加密货币纳入经济发展战略',
    summary: '迪拜政府宣布将区块链和加密货币技术纳入其2030年经济发展战略，推动金融创新。',
    source: '中东区块链政策',
    publishDate: DateTime.now().subtract(const Duration(days: 54)),
  ),
  CryptoNews(
    title: 'Chainlink预言机使用量突破1000个项目',
    summary: '去中心化预言机网络Chainlink宣布其服务已被超过1000个区块链项目采用，创下新纪录。',
    source: '区块链基础设施观察',
    publishDate: DateTime.now().subtract(const Duration(days: 55)),
  ),
  CryptoNews(
    title: '美国最大零售商沃尔玛申请加密货币支付专利',
    summary: '沃尔玛申请了一项使用加密货币进行支付的专利，可能为未来在其平台接受加密货币做准备。',
    source: '零售业区块链创新',
    publishDate: DateTime.now().subtract(const Duration(days: 56)),
  ),
  CryptoNews(
    title: 'Polkadot生态系统首次跨链资产转移成功',
    summary: 'Polkadot网络上的平行链Acala和Moonbeam成功实现了首次跨链资产转移，标志着生态系统的重要进展。',
    source: 'Polkadot生态周报',
    publishDate: DateTime.now().subtract(const Duration(days: 57)),
  ),
  CryptoNews(
    title: '全球最大资产管理公司贝莱德开始交易比特币期货',
    summary: '贝莱德在其管理的两只基金中开始交易比特币期货，进一步推动机构对加密资产的接受。',
    source: '华尔街加密动向',
    publishDate: DateTime.now().subtract(const Duration(days: 58)),
  ),
  CryptoNews(
    title: '闪电网络容量突破3000比特币',
    summary: '比特币闪电网络的总容量首次突破3000比特币，显示第二层支付解决方案的持续增长。',
    source: '比特币扩容观察',
    publishDate: DateTime.now().subtract(const Duration(days: 59)),
  ),
  CryptoNews(
    title: '欧洲最大电信公司开始接受比特币支付',
    summary: '德国电信宣布将接受比特币作为手机话费的支付方式，成为欧洲采用加密货币的先锋。',
    source: '欧洲加密支付创新',
    publishDate: DateTime.now().subtract(const Duration(days: 60)),
  ),
  CryptoNews(
    title: 'DeFi总锁仓价值突破2000亿美元',
    summary: '去中心化金融（DeFi）项目的总锁仓价值突破2000亿美元大关，创下历史新高。',
    source: 'DeFi数据分析',
    publishDate: DateTime.now().subtract(const Duration(days: 61)),
  ),
];